[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Force the plugin to ignore form processing if none exist
[build.environment]
  NEXT_DISABLE_NETLIFY_FORMS = "true"
