import {
  DoINeedToRegisterForVatKenya,
  EtimsAccountLocked,
  EtimsComplianceChecklist,
  EtimsDownOfflineInvoicing,
  EtimsInvoiceRejected,
  EtimsInvoicingGuide,
  EtimsMandateGuide,
  EtimsOnboardingGuide,
  EtimsPendingSync,
  EtimsPenalty50000PerMonthKenya,
  Faq,
  FinanceActVatChangesKenya,
  HowToApplyForKraPin,
  HowToCalculateVatInKenya,
  HowToFileVatReturnOnItax,
  HowToRegisterForVatInKenya,
  IcmsExportGuide,
  InputVatDeductionGuide,
  ItaxPortalNotWorking,
  KPLCBlackoutEtimsCompliance,
  KraPenaltyForLateVatFiling,
  KraPinNotWorking,
  KraStatusCode500ItaxErrors,
  KraTaxAmnesty2026,
  KraVatAuditProcess,
  KraVatFilingDeadlineAugust2026,
  KraVatPenaltiesReference,
  MpesaErrorCodes,
  NilReturnsTaxAmnesty,
  SafaricomNotWorking,
  SmallTaxpayerRegimeKenya,
  TaxComplianceCertificateKenya,
  VatAutoPopulatedReturn,
  VatBadDebtRefundKenya,
  VatDeregistrationKenya,
  VatDigitalServicesKenya,
  VatFintechDigitalPaymentsKenya,
  VatForConstructionRealEstateKenya,
  VatForImportersKenya,
  VatForLandlordsKenya,
  VatForNgosKenya,
  VatForRestaurantsHospitality,
  VatForStartupsTechBusinesses,
  VatLabourOutsourcingKenya,
  VatRatesKenya,
  VatRefundGuideKenya,
  VatRegistrationChecklist,
  VatReturnFilingChecklist,
  VatSpecialTableRisks,
  VatThresholdKenya,
  VatVsTurnoverTax,
  WhatHappensIfIDonTRegisterForVat,
  WithholdingVatKenya
} from "./index"

export interface ResourceMeta {
  title: string
  description: string
  canonical: string
}

export const resourceComponents: Record<string, React.ComponentType> = {
  "do-i-need-to-register-for-vat-kenya": DoINeedToRegisterForVatKenya,
  "etims-account-locked": EtimsAccountLocked,
  "etims-compliance-checklist": EtimsComplianceChecklist,
  "etims-down-offline-invoicing": EtimsDownOfflineInvoicing,
  "etims-invoice-rejected": EtimsInvoiceRejected,
  "etims-mandate-guide": EtimsMandateGuide,
  "etims-invoicing-guide": EtimsInvoicingGuide,
  "etims-onboarding-guide": EtimsOnboardingGuide,
  "etims-pending-sync": EtimsPendingSync,
  "etims-penalty-50000-per-month-kenya": EtimsPenalty50000PerMonthKenya,
  "faq": Faq,
  "finance-act-vat-changes-kenya": FinanceActVatChangesKenya,
  "how-to-apply-for-kra-pin": HowToApplyForKraPin,
  "icms-export-guide": IcmsExportGuide,
  "how-to-calculate-vat-in-kenya": HowToCalculateVatInKenya,
  "how-to-file-vat-return-on-itax": HowToFileVatReturnOnItax,
  "how-to-register-for-vat-in-kenya": HowToRegisterForVatInKenya,
  "input-vat-deduction-guide": InputVatDeductionGuide,
  "itax-portal-not-working": ItaxPortalNotWorking,
  "kplc-blackout-etims-compliance": KPLCBlackoutEtimsCompliance,
  "kra-penalty-for-late-vat-filing": KraPenaltyForLateVatFiling,
  "kra-pin-not-working": KraPinNotWorking,
  "kra-status-code-500-itax-errors": KraStatusCode500ItaxErrors,
  "kra-tax-amnesty-2026": KraTaxAmnesty2026,
  "kra-vat-audit-process": KraVatAuditProcess,
  "kra-vat-filing-deadline-august-2026": KraVatFilingDeadlineAugust2026,
  "kra-vat-penalties-reference": KraVatPenaltiesReference,
  "mpesa-error-codes": MpesaErrorCodes,
  "nil-returns-tax-amnesty": NilReturnsTaxAmnesty,
  "safaricom-not-working": SafaricomNotWorking,
  "small-taxpayer-regime-kenya": SmallTaxpayerRegimeKenya,
  "tax-compliance-certificate-kenya": TaxComplianceCertificateKenya,
  "vat-auto-populated-return": VatAutoPopulatedReturn,
  "vat-bad-debt-refund-kenya": VatBadDebtRefundKenya,
  "vat-deregistration-kenya": VatDeregistrationKenya,
  "vat-digital-services-kenya": VatDigitalServicesKenya,
  "vat-fintech-digital-payments-kenya": VatFintechDigitalPaymentsKenya,
  "vat-for-construction-real-estate-kenya": VatForConstructionRealEstateKenya,
  "vat-for-importers-kenya": VatForImportersKenya,
  "vat-for-landlords-kenya": VatForLandlordsKenya,
  "vat-for-ngos-kenya": VatForNgosKenya,
  "vat-for-restaurants-hospitality": VatForRestaurantsHospitality,
  "vat-for-startups-tech-businesses": VatForStartupsTechBusinesses,
  "vat-labour-outsourcing-kenya": VatLabourOutsourcingKenya,
  "vat-rates-kenya": VatRatesKenya,
  "vat-threshold-kenya": VatThresholdKenya,
  "vat-refund-guide-kenya": VatRefundGuideKenya,
  "vat-registration-checklist": VatRegistrationChecklist,
  "vat-return-filing-checklist": VatReturnFilingChecklist,
  "vat-special-table-risks": VatSpecialTableRisks,
  "vat-vs-turnover-tax": VatVsTurnoverTax,
  "what-happens-if-i-don-t-register-for-vat": WhatHappensIfIDonTRegisterForVat,
  "withholding-vat-kenya": WithholdingVatKenya,
}

export const resourceMeta: Record<string, ResourceMeta> = {
  "do-i-need-to-register-for-vat-kenya": {
    title: "Do I Need to Register for VAT Kenya? Threshold & Rules 2026",
    description: "Unsure if your business needs VAT registration? Learn the KES 5M threshold, penalties for late registration, and how to check your obligation.",
    canonical: "/resources/do-i-need-to-register-for-vat-kenya/",
  },
  "etims-account-locked": {
    title: "eTIMS Account Locked? Unlock It Now (Kenya 2026)",
    description: "Your eTIMS device is locked after 7 days without syncing. Learn why KRA locks accounts, how to unlock via Device Management, and avoid future lockouts.",
    canonical: "/resources/etims-account-locked/",
  },
  "etims-compliance-checklist": {
    title: "eTIMS Compliance Checklist Kenya 2026 — Daily & Monthly",
    description: "KRA eTIMS compliance checklist covering daily sales uploads, device maintenance, invoice issuance, and stock reconciliation. Audit-ready in 10 minutes.",
    canonical: "/resources/etims-compliance-checklist/",
  },
  "etims-down-offline-invoicing": {
    title: "KRA eTIMS Down? Invoice Offline Now — Avoid the 7-Day Lockout",
    description: "KRA eTIMS down or offline? Keep issuing invoices now, sync when the portal recovers, and avoid the 7-day device lockout and KES 50,000/month compliance fines.",
    canonical: "/resources/etims-down-offline-invoicing/",
  },
  "etims-invoice-rejected": {
    title: "eTIMS Invoice Rejected? Fix It Fast (Kenya 2026)",
    description: "Your eTIMS invoice was rejected by KRA — here's why and exactly how to fix common errors like invalid PIN, duplicate invoice, and stock mismatch.",
    canonical: "/resources/etims-invoice-rejected/",
  },
  "etims-mandate-guide": {
    title: "eTIMS Mandate Kenya 2026: Who Must Comply & When",
    description: "Complete guide to the KRA eTIMS mandate: which businesses must register, compliance deadlines, penalties for non-compliance, and how to onboard.",
    canonical: "/resources/etims-mandate-guide/",
  },
  "etims-invoicing-guide": {
    title: "eTIMS Compliant Invoice Guide Kenya 2026",
    description: "How to issue a KRA-compliant eTIMS invoice with required fields, QR code, tax rates, and common formatting mistakes that trigger rejections.",
    canonical: "/resources/etims-invoicing-guide/",
  },
  "etims-onboarding-guide": {
    title: "eTIMS Onboarding Guide Kenya 2026: Register Step by Step",
    description: "Step-by-step eTIMS registration guide for Kenyan businesses. How to get your ECD device, upload stock, and start issuing compliant invoices.",
    canonical: "/resources/etims-onboarding-guide/",
  },
  "etims-pending-sync": {
    title: "eTIMS Pending Sync? Fix It Before the 7-Day Lockout",
    description: "eTIMS stuck on 'pending sync'? Learn why invoices don't upload to KRA, how to force a manual sync, and how to avoid the 7-day device lockout.",
    canonical: "/resources/etims-pending-sync/",
  },
  "etims-penalty-50000-per-month-kenya": {
    title: "eTIMS Penalty KES 50,000/Month — Avoid It Now 2026",
    description: "KRA charges KES 50,000/month for eTIMS non-compliance. Learn what triggers the penalty, how to appeal, and how to avoid it entirely.",
    canonical: "/resources/etims-penalty-50000-per-month-kenya/",
  },
  "faq": {
    title: "KRA VAT FAQ — Common Questions Answered 2026",
    description: "Frequently asked questions about KRA VAT registration, eTIMS, filing deadlines, penalties, refunds, and amnesty. Updated for 2026.",
    canonical: "/resources/faq/",
  },
  "finance-act-vat-changes-kenya": {
    title: "Finance Act 2025 & 2026 VAT Changes Kenya Explained",
    description: "All VAT changes from the Finance Act 2025 and 2026: digital services tax, withholding VAT, amnesty provisions, and what they mean for your business.",
    canonical: "/resources/finance-act-vat-changes-kenya/",
  },
  "how-to-apply-for-kra-pin": {
    title: "How to Apply for a KRA PIN in Kenya 2026 (Online Guide)",
    description: "Step-by-step guide to applying for a KRA PIN online via iTax. Covers individual and business registration, required documents, and troubleshooting.",
    canonical: "/resources/how-to-apply-for-kra-pin/",
  },
  "icms-export-guide": {
    title: "iCMS Export Guide 2026: VAT for Kenyan Exporters",
    description: "Complete iCMS export declaration guide for Kenyan businesses. Learn VAT implications, zero-rating requirements, documentation, and KRA compliance.",
    canonical: "/resources/icms-export-guide/",
  },
  "how-to-calculate-vat-in-kenya": {
    title: "How to Calculate 16% VAT in Kenya (Calculator & Formula)",
    description: "Learn how to calculate 16% VAT in Kenya — including VAT exclusive, inclusive, and reverse calculations. Free formula guide with KES examples.",
    canonical: "/resources/how-to-calculate-vat-in-kenya/",
  },
  "how-to-file-vat-return-on-itax": {
    title: "How to File VAT Return on KRA iTax (Step-by-Step 2026)",
    description: "Step-by-step guide to filing your monthly VAT return on KRA iTax. Covers auto-populated returns, common errors, and what to do when the portal is down.",
    canonical: "/resources/how-to-file-vat-return-on-itax/",
  },
  "how-to-register-for-vat-in-kenya": {
    title: "How to Register for VAT in Kenya on iTax (2026 Guide)",
    description: "Complete step-by-step guide to registering for VAT in Kenya via iTax. Documents needed, timeline, KES 5M threshold, and what happens after registration.",
    canonical: "/resources/how-to-register-for-vat-in-kenya/",
  },
  "input-vat-deduction-guide": {
    title: "Input VAT Deduction Kenya 2026 — What Can You Claim?",
    description: "Complete guide to input VAT deductions in Kenya. Learn which expenses qualify, what documents KRA requires, and common pitfalls that trigger audit flags.",
    canonical: "/resources/input-vat-deduction-guide/",
  },
  "itax-portal-not-working": {
    title: "KRA iTax Down? Fix It Now — Status & Workarounds (2026)",
    description: "Is KRA iTax down? Check current portal status, fix common errors (status code 500, OTP not received, login failed), and workarounds for outages.",
    canonical: "/resources/itax-portal-not-working/",
  },
  "kplc-blackout-etims-compliance": {
    title: "KPLC Blackout? Keep Your eTIMS & VAT Compliance Intact 2026",
    description: "A power cut doesn't pause your KRA obligations. Invoice offline, pay via M-Pesa on your phone, and protect yourself from the 7-day eTIMS lockout.",
    canonical: "/resources/kplc-blackout-etims-compliance/",
  },
  "kra-penalty-for-late-vat-filing": {
    title: "KRA Penalty for Late VAT Filing — Waive It Fast 2026",
    description: "KRA charges 5% late filing penalty + 1% monthly interest on overdue VAT. Learn how much you owe and how to apply for a penalty waiver or amnesty.",
    canonical: "/resources/kra-penalty-for-late-vat-filing/",
  },
  "kra-pin-not-working": {
    title: "KRA PIN Not Working? Fix It Now (Kenya 2026)",
    description: "Your KRA PIN application is stuck or not working? Common causes include ID number mismatches, system errors, and processing delays. Step-by-step fixes.",
    canonical: "/resources/kra-pin-not-working/",
  },
  "kra-status-code-500-itax-errors": {
    title: "KRA Status Code 500 — Fix iTax Errors & Portal Crashes Fast",
    description: "KRA status code 500 means the iTax server is down or timing out. Here's what causes it, how to fix it, and workarounds when the portal is unavailable.",
    canonical: "/resources/kra-status-code-500-itax-errors/",
  },
  "kra-tax-amnesty-2026": {
    title: "KRA Tax Amnesty 2026 — Waive Penalties Now (Dec 31)",
    description: "Complete guide to the KRA tax amnesty 2026. Waives 100% of penalties and interest on pre-2026 tax debt. Eligibility, how to apply, deadline December 31.",
    canonical: "/resources/kra-tax-amnesty-2026/",
  },
  "kra-vat-audit-process": {
    title: "KRA VAT Audit Process 2026 — What to Expect & Prepare",
    description: "What happens during a KRA VAT audit? From notification to final assessment. Learn your rights, required documents, and how to survive with minimal penalties.",
    canonical: "/resources/kra-vat-audit-process/",
  },
  "kra-vat-filing-deadline-august-2026": {
    title: "KRA VAT Filing Deadline August 2026 — File Before the 20th",
    description: "KRA VAT return for July 2026 is due August 20, 2026. Late filing triggers a 5% penalty plus 1% monthly interest. File on time with our step-by-step guide.",
    canonical: "/resources/kra-vat-filing-deadline-august-2026/",
  },
  "kra-vat-penalties-reference": {
    title: "KRA VAT Penalties 2026 — Complete Reference Table",
    description: "KRA VAT penalties reference table for 2026: late filing (5%), late payment (1%/month), eTIMS non-compliance (KES 50K/mo), and waiver eligibility.",
    canonical: "/resources/kra-vat-penalties-reference/",
  },
  "mpesa-error-codes": {
    title: "M-Pesa Error Codes 2026 — Fix MR101, MR105 Fast",
    description: "M-Pesa error codes explained: MR101, MR102, MR105, MR110, 'transaction failed', and PIN-locked. What each means, how to fix it, and paying KRA VAT.",
    canonical: "/resources/mpesa-error-codes/",
  },
  "nil-returns-tax-amnesty": {
    title: "How to File Nil Returns on KRA iTax (2026) + Amnesty Guide",
    description: "Step-by-step guide to filing nil VAT returns on KRA iTax, how they interact with the 2026 tax amnesty, and common mistakes that trigger KRA queries.",
    canonical: "/resources/nil-returns-tax-amnesty/",
  },
  "safaricom-not-working": {
    title: "Safaricom Not Working? Fix It Now — Status & M-Pesa Workarounds",
    description: "Safaricom network or M-Pesa down? Check the current outage status, how downtime affects M-Pesa payments and KRA VAT remittance, and what to do.",
    canonical: "/resources/safaricom-not-working/",
  },
  "small-taxpayer-regime-kenya": {
    title: "Small Taxpayer Regime Kenya 2026 — VAT & TOT Guide",
    description: "Kenya's small taxpayer regime explained: turnover tax vs VAT, registration thresholds, simplified rules, and which regime suits your business.",
    canonical: "/resources/small-taxpayer-regime-kenya/",
  },
  "tax-compliance-certificate-kenya": {
    title: "Get Your Tax Compliance Certificate (TCC) Fast — Kenya 2026",
    description: "How to get your KRA Tax Compliance Certificate (TCC) online via iTax: requirements, processing time, common errors, and why your TCC may be rejected.",
    canonical: "/resources/tax-compliance-certificate-kenya/",
  },
  "vat-auto-populated-return": {
    title: "KRA Auto-Populated VAT Return 2026 — What to Check",
    description: "KRA auto-populates VAT returns with eTIMS sales data. Learn what's included, how to verify accuracy, correct errors, and avoid penalties for mismatched figures.",
    canonical: "/resources/vat-auto-populated-return/",
  },
  "vat-bad-debt-refund-kenya": {
    title: "VAT Bad Debt Relief Kenya 2026 — Refund on Unpaid Invoices",
    description: "Claim VAT back on unpaid invoices under Kenya's bad debt relief rules: eligibility, time limits, how to apply, and what happens if the customer later pays.",
    canonical: "/resources/vat-bad-debt-refund-kenya/",
  },
  "vat-deregistration-kenya": {
    title: "VAT Deregistration Kenya 2026 — Cancel on iTax",
    description: "How to cancel your VAT registration in Kenya. When you can deregister, how to apply on iTax, what happens to your eTIMS device, and outstanding returns.",
    canonical: "/resources/vat-deregistration-kenya/",
  },
  "vat-digital-services-kenya": {
    title: "VAT on Digital Services in Kenya 2026 — Complete Guide",
    description: "VAT on digital services in Kenya covers SaaS, e-books, streaming, and courses. Learn who must register, the 16% rate, and compliance for foreign providers.",
    canonical: "/resources/vat-digital-services-kenya/",
  },
  "vat-fintech-digital-payments-kenya": {
    title: "VAT on Fintech & Digital Payments Kenya 2026",
    description: "How VAT applies to fintech in Kenya: 16% on mobile money (M-Pesa) fees, payment commissions, merchant charges, and KRA compliance for digital payments.",
    canonical: "/resources/vat-fintech-digital-payments-kenya/",
  },
  "vat-for-construction-real-estate-kenya": {
    title: "VAT for Construction & Real Estate Kenya 2026",
    description: "VAT for construction and real estate in Kenya: reverse VAT on imported services, mixed-use apportionment, contractor obligations, and recent court rulings.",
    canonical: "/resources/vat-for-construction-real-estate-kenya/",
  },
  "vat-for-importers-kenya": {
    title: "VAT for Importers in Kenya 2026 — Import VAT Guide",
    description: "Complete guide to import VAT in Kenya: rates, customs clearance, VAT deferment, what to do if you overpay, and compliance requirements for regular importers.",
    canonical: "/resources/vat-for-importers-kenya/",
  },
  "vat-for-landlords-kenya": {
    title: "VAT for Landlords Kenya 2026 — Do I Charge VAT on Rent?",
    description: "Do landlords charge VAT on rental income in Kenya? Learn when commercial rent exceeds the KES 5M threshold, VAT exemptions, and registration requirements.",
    canonical: "/resources/vat-for-landlords-kenya/",
  },
  "vat-for-ngos-kenya": {
    title: "VAT for NGOs in Kenya 2026 — Exemptions & Compliance",
    description: "VAT rules for NGOs and charities in Kenya: which supplies are exempt, how to claim refunds, compliance obligations, and mistakes that trigger KRA audits.",
    canonical: "/resources/vat-for-ngos-kenya/",
  },
  "vat-for-restaurants-hospitality": {
    title: "VAT for Restaurants & Hospitality in Kenya 2026 Guide",
    description: "VAT rules for restaurants, hotels, and hospitality businesses in Kenya. Rates for food vs alcohol, eTIMS requirements, and input VAT on perishable supplies.",
    canonical: "/resources/vat-for-restaurants-hospitality/",
  },
  "vat-for-startups-tech-businesses": {
    title: "VAT for Startups & Tech Businesses Kenya 2026",
    description: "VAT compliance guide for Kenyan startups and tech businesses: registration thresholds, digital services tax, input VAT on software, and early mistakes.",
    canonical: "/resources/vat-for-startups-tech-businesses/",
  },
  "vat-labour-outsourcing-kenya": {
    title: "VAT on Labour Outsourcing & Staff Costs Kenya 2026",
    description: "VAT on labour outsourcing and staff costs in Kenya: the distinction between supply of staff vs supply of services, with KRA guidance and tribunal cases.",
    canonical: "/resources/vat-labour-outsourcing-kenya/",
  },
  "vat-rates-kenya": {
    title: "VAT Rates in Kenya 2026 — 16%, Zero-Rated & Exempt",
    description: "Kenya's VAT rates for 2026: 16% standard, zero-rated supplies (food, exports, medicine, agricultural inputs), exempt services (insurance, financial, education).",
    canonical: "/resources/vat-rates-kenya/",
  },
  "vat-threshold-kenya": {
    title: "VAT Threshold Kenya 2026 — KES 5M or 8M?",
    description: "Kenya's VAT registration threshold is KES 5 million annual turnover. Learn who must register, the voluntary threshold debate, and late-registration penalties.",
    canonical: "/resources/vat-threshold-kenya/",
  },
  "vat-refund-guide-kenya": {
    title: "VAT Refund Guide Kenya 2026 — How to Claim Your Money",
    description: "How to claim a VAT refund from KRA. Amended return vs refund application, processing time, required documents, and common reasons for refund rejection.",
    canonical: "/resources/vat-refund-guide-kenya/",
  },
  "vat-registration-checklist": {
    title: "VAT Registration Checklist Kenya 2026 — Documents Needed",
    description: "Complete VAT registration checklist for Kenya: required documents, business details, tax agent appointment letter, and common application mistakes to avoid.",
    canonical: "/resources/vat-registration-checklist/",
  },
  "vat-return-filing-checklist": {
    title: "VAT Return Filing Checklist Kenya 2026 — Monthly Guide",
    description: "Monthly VAT return filing checklist: sales data, input VAT documents, eTIMS reconciliation, common errors, and what to check before submitting on iTax.",
    canonical: "/resources/vat-return-filing-checklist/",
  },
  "vat-special-table-risks": {
    title: "KRA VAT Special Table — Risks & How to Avoid Being Flagged",
    description: "The KRA VAT Special Table fast-tracks your refund but increases audit risk. Learn how it works, common triggers that get you flagged, and how to stay compliant.",
    canonical: "/resources/vat-special-table-risks/",
  },
  "vat-vs-turnover-tax": {
    title: "Turnover Tax vs VAT in Kenya — Which Applies to You 2026",
    description: "Turnover tax (3% of gross sales) vs VAT (16%, input deductible) — which applies to your business? Thresholds, compliance burden, and switching rules.",
    canonical: "/resources/vat-vs-turnover-tax/",
  },
  "what-happens-if-i-don-t-register-for-vat": {
    title: "What Happens If I Don't Register for VAT in Kenya? 2026",
    description: "Penalties for failing to register for VAT in Kenya: backdated tax assessments, 5% late filing penalties, 1% monthly interest, and potential KRA prosecution.",
    canonical: "/resources/what-happens-if-i-don-t-register-for-vat/",
  },
  "withholding-vat-kenya": {
    title: "Withholding VAT Kenya 2026 — Complete Guide",
    description: "Withholding VAT in Kenya requires buyers to deduct 2% VAT at source on certain supplies. Learn who must withhold, how to remit, and how suppliers claim credit.",
    canonical: "/resources/withholding-vat-kenya/",
  },
}
